{application, postlock_server,
 [{description,"Postlock server"},
  {vsn,"0.0001"},
  {modules,[
    plCallbackMgr,
    plGateway, 
    plRegistry,
    plState, 
    plSession,
    plApp,
    plApi]},
  {registered, [plRegistry]},
  {mod,{plApp,[]}},
  {env, []},
  {applications,[kernel, stdlib, yaws, yapp]}]}.
